"""add qa_questions table

Revision ID: 0216422681fc
Revises: a62c3f780664
Create Date: 2026-08-28 23:30:42.917231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0216422681fc'
down_revision: Union[str, None] = 'a62c3f780664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_image', sa.String(), nullable=False),
    sa.Column('choice_a_image', sa.String(), nullable=False),
    sa.Column('choice_b_image', sa.String(), nullable=False),
    sa.Column('choice_c_image', sa.String(), nullable=False),
    sa.Column('choice_d_image', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A','B','C','D')", name='ck_qa_correct_answer_letter'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'question_number', name='uq_qa_source_file_question_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_questions')
    # ### end Alembic commands ###
