"""add needs_review and ocr_confidence

Revision ID: 15cb2b399c73
Revises: 9a1aefc61d8d
Create Date: 2026-08-23 23:30:17.701168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15cb2b399c73'
down_revision: Union[str, None] = '9a1aefc61d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('questions', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'ocr_confidence')
    op.drop_column('questions', 'needs_review')
    # ### end Alembic commands ###
