"""make source_page nullable

Revision ID: 4a85dc4a6e9d
Revises: 3e688a7fbab2
Create Date: 2026-08-24 22:41:10.656198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a85dc4a6e9d'
down_revision: Union[str, None] = '3e688a7fbab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'source_page',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'source_page',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
