"""remove task assignment, add image questions

Revision ID: a62c3f780664
Revises: 4a85dc4a6e9d
Create Date: 2026-08-24 22:51:29.968647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a62c3f780664'
down_revision: Union[str, None] = '4a85dc4a6e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A','B','C','D')", name='ck_image_correct_answer_letter'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'question_number', name='uq_image_source_file_question_number')
    )
    op.drop_constraint(op.f('users_assigned_task_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_assigned_task_id_fkey'), 'users', 'tasks', ['assigned_task_id'], ['id'])
    op.drop_table('image_questions')
    # ### end Alembic commands ###
